service: gerenciamento-financas-service

provider:
  name: aws
  runtime: nodejs10.x
  region: sa-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  primaryInfoSubmission:
    memorySize: 128
    description: Submit user primary informations.
    role: arn:aws:iam::146766432310:role/gerenciamento-financas-service-dev-sa-east-1-lambdaRole
    handler: api/user/primary-info.primaryInfoSubmit
    events:
      - http:
          path: /api/user
          method: post
  userExpensesSubmission:
    memorySize: 128
    description: Submit user expenses.
    role: arn:aws:iam::146766432310:role/gerenciamento-financas-service-dev-sa-east-1-lambdaRole
    handler: api/user/expenses.expensesSubmit
    events:
      - http:
          path: /api/user/expenses
          method: post
  retrieveUserInfo:
    memorySize: 128
    description: Retrieve user informations.
    handler: api/user/user.retrieve
    events:
      - http:
          path: /api/user/{email_id}
          method: get
  retrieveUserExpenses:
    memorySize: 128
    description: Retrieve user informations.
    role: arn:aws:iam::146766432310:role/gerenciamento-financas-service-dev-sa-east-1-lambdaRole
    handler: api/user/user.retrieveExpensesOnDate
    events:
      - http:
          path: /api/user/{email_id}/date/{date}
          method: get
#  retrieveUserExpenses:
#    memorySize: 128
#    description: Retrieve user expenses on passed date.
#    handler: api/user/user.retrieveExpensesOnDate
#    event:
#      - http:
#          path: /api/user/{date}
#          method: get
plugins:
  - serverless-offline
